# Generated by Django 5.0 on 2024-01-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=20, verbose_name='Название контакта')),
                ('contact_link', models.CharField(max_length=20, verbose_name='Контакт')),
                ('contact_icon', models.ImageField(blank=True, null=True, upload_to='./img/icons', verbose_name='Иконка для десктопной версии')),
                ('contact_icon_adaptive', models.ImageField(blank=True, null=True, upload_to='./img/icons', verbose_name='Иконка для адаптивной версии')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['contact_title'],
            },
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=20, verbose_name='Название проекта')),
                ('owner_name', models.CharField(max_length=100, verbose_name='ФИО или Название юр.лица')),
                ('unp', models.CharField(max_length=9, verbose_name='УНП')),
                ('country', models.CharField(max_length=25, verbose_name='Страна')),
                ('postcode', models.CharField(max_length=6, verbose_name='Индекс')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house', models.CharField(max_length=5, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Авторское право',
                'verbose_name_plural': 'Авторские права',
                'ordering': ['site_name'],
            },
        ),
    ]
