# Generated by Django 5.0 on 2024-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название секции')),
            ],
            options={
                'verbose_name': 'Название секции',
                'verbose_name_plural': 'Название секций',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('news_body', models.CharField(max_length=255, verbose_name='Содержание')),
                ('news_img', models.ImageField(blank=True, null=True, upload_to='./new/img', verbose_name='Картинка для новости')),
                ('news_video', models.FileField(blank=True, null=True, upload_to='./new/vedeo', verbose_name='Видео для новости')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='./new/vedeo/img', verbose_name='Картинка, покрывающая видео')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации новости')),
                ('news_sections', models.ManyToManyField(related_name='news_section', to='news.newssection')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date_published'],
            },
        ),
    ]
