# Generated by Django 5.0 on 2024-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название секции')),
            ],
            options={
                'verbose_name': 'Название секции',
                'verbose_name_plural': 'Название секций',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('blog_body', models.CharField(max_length=255, verbose_name='Содержание')),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='./blog/img', verbose_name='Картинка для блога')),
                ('blog_video', models.FileField(blank=True, null=True, upload_to='./blog/vedeo', verbose_name='Видео для блога')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='./blog/vedeo/img', verbose_name='Картинка, покрывающая видео')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации блога')),
                ('blog_sections', models.ManyToManyField(related_name='blog_sections', to='blog.blogssection')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-date_published'],
            },
        ),
    ]
