# Generated by Django 5.0 on 2024-01-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название ресурса')),
                ('description', models.TextField(verbose_name='Описание ресурса')),
                ('file', models.FileField(upload_to='./video', verbose_name='Видео о ресурсе')),
                ('data_add_video', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления видео')),
                ('image', models.ImageField(upload_to='./preview_img', verbose_name='Превью-картинка для видео')),
            ],
            options={
                'verbose_name': 'Блок "О ресурсе"',
                'verbose_name_plural': 'Блок "О ресурсе"',
            },
        ),
        migrations.CreateModel(
            name='SomeFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Определение термина или описание факта')),
            ],
            options={
                'verbose_name': 'Блок "Немного фактов"',
                'verbose_name_plural': 'Блок "Немного фактов"',
            },
        ),
    ]
